version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pharmacy_sys_pg
    environment:
      POSTGRES_USER: pharmacy
      POSTGRES_PASSWORD: pharmacy
      POSTGRES_DB: pharmacy_sys
    ports:
      - "5433:5432"
    volumes:
      - pharmacy_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmacy -d pharmacy_sys"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pharmacy_pg_data:
