import { z } from 'zod';
import { ActiveStatus, ProductKind, TaxMode } from '@prisma/client';

export const createMedicineSchema = z.object({
  name: z.string().min(1).max(255),
  nameAr: z.string().max(255).nullable().optional(),
  genericName: z.string().min(1).max(255),
  qrCode: z.string().min(1).max(191),
  description: z.string().min(1),
  status: z.nativeEnum(ActiveStatus),
  supplierId: z.coerce.number().int().positive(),
  vendorId: z.coerce.number().int().positive().nullable().optional(),
  price: z.coerce.number().min(0).default(0),
  buyPrice: z.coerce.number().min(0).default(0),
  quantity: z.coerce.number().int().min(0).default(0),
  instock: z.coerce.number().int().min(0).default(0),
  strength: z.string().max(255).nullable().optional(),
  leafId: z.coerce.number().int().positive().nullable().optional(),
  typeId: z.coerce.number().int().positive().nullable().optional(),
  purchaseUnitId: z.coerce.number().int().positive().nullable().optional(),
  sellUnitId: z.coerce.number().int().positive().nullable().optional(),
  unitConversion: z.coerce.number().positive().default(1),
  shelf: z.string().max(255).nullable().optional(),
  categoryIds: z.array(z.coerce.number().int().positive()).default([]),
  barcodes: z.array(z.string().min(1).max(64)).default([]),
  kind: z.nativeEnum(ProductKind).optional().default('inventory'),
  vat: z.coerce.number().min(0).default(0),
  discount: z.coerce.number().min(0).default(0),
  taxMode: z.nativeEnum(TaxMode).nullable().optional(),
  image: z.string().max(500).nullable().optional(),
  igta: z.string().max(255).nullable().optional(),
  hnsCode: z.string().max(255).nullable().optional(),
  reorderLevel: z.coerce.number().int().min(0).default(0),
  minStock: z.coerce.number().int().min(0).default(0),
  maxStock: z.coerce.number().int().min(0).default(0),
});

export const updateMedicineSchema = z.object({
  name: z.string().min(1).max(255).optional(),
  nameAr: z.string().max(255).nullable().optional(),
  genericName: z.string().min(1).max(255).optional(),
  qrCode: z.string().min(1).max(191).optional(),
  description: z.string().min(1).optional(),
  status: z.nativeEnum(ActiveStatus).optional(),
  supplierId: z.coerce.number().int().positive().optional(),
  vendorId: z.coerce.number().int().positive().nullable().optional(),
  price: z.coerce.number().min(0).optional(),
  buyPrice: z.coerce.number().min(0).optional(),
  quantity: z.coerce.number().int().min(0).optional(),
  instock: z.coerce.number().int().min(0).optional(),
  strength: z.string().max(255).nullable().optional(),
  leafId: z.coerce.number().int().positive().nullable().optional(),
  typeId: z.coerce.number().int().positive().nullable().optional(),
  purchaseUnitId: z.coerce.number().int().positive().nullable().optional(),
  sellUnitId: z.coerce.number().int().positive().nullable().optional(),
  unitConversion: z.coerce.number().positive().optional(),
  shelf: z.string().max(255).nullable().optional(),
  categoryIds: z.array(z.coerce.number().int().positive()).optional(),
  barcodes: z.array(z.string().min(1).max(64)).optional(),
  kind: z.nativeEnum(ProductKind).optional(),
  vat: z.coerce.number().min(0).optional(),
  discount: z.coerce.number().min(0).optional(),
  taxMode: z.nativeEnum(TaxMode).nullable().optional(),
  image: z.string().max(500).nullable().optional(),
  igta: z.string().max(255).nullable().optional(),
  hnsCode: z.string().max(255).nullable().optional(),
  reorderLevel: z.coerce.number().int().min(0).optional(),
  minStock: z.coerce.number().int().min(0).optional(),
  maxStock: z.coerce.number().int().min(0).optional(),
});

export const suggestBarcodeSchema = z.object({
  prefix: z.string().max(8).optional(),
});

export const medicineListQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
  search: z.string().max(255).optional(),
  categoryId: z.coerce.number().int().positive().optional(),
  supplierId: z.coerce.number().int().positive().optional(),
});
